<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['CRMCSS'];
    echo $head['BOXCSS'];
    echo $head['THEME'];
    echo $head['JQTABLE'];
    echo $head['JQBOX'];

?>
<script language="javascript" type="text/javascript" src="translation/auswertungen.lng"></script>
<script>
    $( document ).ready( function(){
        var language = kivi.myconfig.countrycode;    
        var initOptions = { theme : 'blue' };
        $.ajax({
            url: 'jqhelp/analysis.php',
            //dataType: 'json',
            type: "POST",
            data: { task: "getBerichte" }
        }).done(function(json) {
            $( '#Bericht' ).selectBoxIt({
                //populate: json  
                populate: $.parseJSON( json.trim() )
            });
            $( '#zusatz' ).hide();
        });  //end getBerichte

        $( '#Bericht' ).change(function() {
            var id  = $( '#Bericht option:selected' ).val();
            $.ajax({
                url: 'jqhelp/analysis.php',
                dataType: 'json',
                type: "POST",
                data: { task:  'initBericht', }
            }).done(function(json) {
                $( '#zusatz' ).empty().append(json);
            })
        })
        $.ajax({                        //"Session"-Vars holen
                url: 'jqhelp/analysis.php',
                dataType: 'json',
                type: "POST",
                data: { task:  'initBericht', }
        }).done(function(json) {
            //var language    = (json['countrycode'])?json['countrycode']:'en';
            var loginCRM    = json['loginCRM'];
         	$( '.ui-widget-content' ).show();
         	$( '#no' ).hide();
            /*var manager     = json['manager'];
            if ( manager ) {
         	       $( '.ui-widget-content' ).show();
         	       $( '#no' ).hide();
            } else {
         	   	   $( '.ui-widget-content' ).hide();
         	       $( '#no' ).show();
            }*/
            $( ".lang" ).each( function(){
                var key = $( this ).attr( "data-lang" );
                $( this ).text( typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
            });
        }) //end initBericht
         
        $( '#make' ).button().click( function() {
            var id  = $( '#Bericht option:selected' ).val();
            var txt = $( '#Bericht option:selected' ).text();
            var start = $( "#StartDate" ).val();
            var stop  = $( "#StopDate" ).val();
            var _top  = $( '#Top' ).val();
            var _art  = $("input[name='topart']:checked").val();
            var _out  = $("input[name='ausgabe']:checked").val();
            var zusatz = '';
            $( '#zusatz :input' ).each( function(e) { zusatz += $(this).attr('name')+':'+$(this).val()+';'; } );
            $.ajax({
                url: 'jqhelp/analysis.php',
                dataType: 'json',
                type: "POST",
                data: { task:  'doBericht', bericht: id, von: start, bis: stop, best: _top, bestart: _art, ausgabe: _out, zusatz: zusatz},
            }).done(function(data) {
            console.log(data['tabelle']);
                $( '#datatable').trigger('destroy');
                $( '#tabelle' ).empty().html(data['tabelle']);
                //$( '#datatable' ).addClass('tablesorter');
                $( '#datatable' ).tablesorter({widthFixed: true, widgets: ['zebra'], widgetOptions : { zebra : [ "even", "odd" ]},debug: true });
                //$( '#datatable head').empty();
                //$( '#datatable body').empty();
                /*$( '#datatable').trigger('destroy',[false, function(){
                                            $( '#datatable thead').html(data['tabelle']['head']);
                                            $( '#datatable').tablesorter(initOptions);
                                      }]);*/
                //$( '#datatable head').empty().html(data['tabelle']['head']);
                //$( '#datatable tbody').empty().html(data['tabelle']['body']);
                $( '#datatable').trigger('update');
                $( '#grafik' ).empty().append(data['grafik']);
                $( '#file' ).empty().append(data['file']);
                $( '#note' ).empty().append(data['note']);
                $( '#msg' ).empty().append(data['msg']);
            });
        }); //end Button make
        $( '#Bericht' ).on('change',function() {
             $.ajax({
                url: 'jqhelp/analysis.php',
                dataType: 'json',
                type: "POST",
                data: { task: 'getZusatzFelder', bericht: this.value },
            }).done(function(data) {
                $( '#note' ).empty().append(data['note']);                
                if ( data['felder'] ) {
                   $( '#zusatz' ).show(); 
                   $( '#zusatz' ).empty().append(data['felder']); 
                } else {
                    $( '#zusatz' ).empty();
                    $( '#zusatz' ).hide();
                }
            });
        });
        $( "#StartDate" ).datepicker($.datepicker.regional[ "de" ]); 
        $( "#StopDate" ).datepicker($.datepicker.regional[ "de" ]);
    }); //end document ready

</script>
<style>
    .buttons { padding: 0.25em;  }
    table { background-color: #ffeda0;
            border-collapse: collapse;
            border: none;
            font-size: 12px;
    }
    thead { background-color: #f3c600;
            font-size: 1.2em;
            font-weight: bold;
    }
    td, th { padding: 0.5em 1em; }
    .line0 { background-color: #fffdb0; }
    .line1 { background-color: #ffdda0;}
    .inline { display: inline-block; vertical-align:top;}
    .block  { display: block; }
</style>
</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:722px; border:0px;">
<h1 class="toplist  ui-widget  ui-corner-all content1" onClick="help('Auswertungen');"><span class='lang' data-lang='HEADLINE'></span></h1><br>

    <br>
    <span class='inline'>
        <span id="BerichtLabel" data-lang='BERICHT' class='lang'></span> 
        <span id="BerichtDrop">
            <select id="Bericht" >
            </select> 
            <input type='radio' name='ausgabe' value='1' id='aus1' checked><label for='aus1' data-lang='TEXT' class='lang'></label>
            <input type='radio' name='ausgabe' value='2' id='aus2'><label for='aus1' data-lang='GRAPH' class='lang'></label>
            <input type='radio' name='ausgabe' value='3' id='aus3'><label for='aus1' data-lang='TXTGRA' class='lang'></label>
            <button id="make"  class="lang buttons" data-lang="MAKE"></button>
        </span><br/>
        <span id='zusatz'></span>
        <span id="Dates">
             <span data-lang='FROM' class='lang'></span><input type="text"  id="StartDate" size='10'>
             <span data-lang='TO'   class='lang'></span><input type="text"  id="StopDate"  size='10'>
             <span data-lang='TOP'  class='lang'></span><input type="text"  id="Top"       class="text ui-widget-content ui-corner-all date" size='5'>
             <span data-lang='SUM'  class='lang'></span><input type='radio' id="Rsum"      name='topart' value='sum' checked>
             <span data-lang='CNT'  class='lang'></span><input type='radio' id="Rcnt"      name='topart' value='cnt'>
        </span>
    </span>
    <span id='note' class='inline' style='font-size:1.2em; margin-left:4em;'></span>
    <br>
    <span id='msg'></span>
    <span id='file'></span>
    <span id='tabelle' class='inline' style="color:#ff5555;">
        <table id='datatable' class='tablesorter' style='margin:0px; cursor:pointer; border:0px;'>
            <thead></thead>
            <tbody></tbody>
        </table>
    </span>
    <span id='grafik' style='border: solid,1px;'></span>
</div>
<!--div id='no' style="display: none"><br><h1 class="toplist  ui-widget  ui-corner-all">Nur für Gruppen-Mitglieder mit Ressourcen-Recht</h1></div-->
<?php echo $menu['end_content']; ?>
</body>
</html>
