<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['CRMCSS'];
    echo $head['FULLCALCSS'];
    echo $head['BOXCSS'];
    echo $head['COLORPICKERCSS'];
    echo $head['JQTIMECSS'];
    echo $head['THEME'];
    echo $head['FULLCALJS'];
    echo $head['JQBOX'];
    echo $head['COLORPICKERJS'];
    echo $head['JQCOOKIE'];
    echo $head['JQTIME']; 
/*************************************************** +++ ToDo ++++*******************************************************
Kategorien und User + All in Tabs darstellen!!!!
Visibility für Gruppen
************************************************************************************************************************/
?>
<script language="javascript" type="text/javascript" src="translation/calendar.lng"></script>
<script>
    var UserGrp = false;
    var NewEvent = false;
    var Category= false;
    var UGs     = new Array();
    var Cat     = new Array();
    var colors  = new Array('#FFFF0C','#FF7400', '#CDEB8B','#6BBA70','#006E2E','#C3D9FF','#0101DF','#4096EE','#356AA0','#FF0096','#DF0101','#B02B2C','#000000');
    $(document).ready(function() {
        var language = kivi.myconfig.countrycode;
        $.ajax({
            url: 'jqhelp/calendar.php',
            dataType: 'json',
            data: { task:  'initCal', }
        }).done(function(json) { 
            var feature_ac_delay     = json['feature_ac_delay'];
            var feature_ac_minlength = json['feature_ac_minlength'];
            var termbegin   = ((json['termbegin'])?json['termbegin']:"07")+":00";
            var termend     = ((json['termend'])?json['termend']:"19")+":00"
            var termseq     = (json['termseq'])?json['termseq']:"30";
            //var language    = (json['countrycode'])?json['countrycode']:'en';
            var loginCRM    = json['loginCRM'];
            var grps        = json['grps'];
            var defaultcal  = json['caltype'];

            $.datepicker.setDefaults($.extend({}, { buttonImageOnly: false, buttonImage:'', showOn: 'focus' }));
            $( "#startDate" ).datepicker(); 
            $( "#endDate" ).datepicker();
            $( "#startTime" ).timepicker({showPeriodLabels: false,hourText:langData[language]['Hour']});
            $( "#endTime" ).timepicker({showPeriodLabels: false,hourText:langData[language]['Hour']});
            $( ".lang" ).each( function(){
                var key = $( this ).attr( "data-lang" );
                if( $( this ).is( ":input" ) ) $( this ).attr( 'title',  typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
                else $( this ).text( typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
            });//end $.each lang
            $( "#dialog" ).dialog({
                autoOpen: false,
                height: 540,
                width: 680,
                modal: true,
                buttons: {
                    "Save": function() {
                        var start = moment($( "#startDate" ).val() + ' ' + $( "#startTime" ).val(),'L LT');
                        var end = moment($( "#endDate" ).val() + ' ' + $( "#endTime" ).val(),'L LT');
                        var start_cur = moment($( "#startDate" ).val() + ' ' + $( "#startTime" ).val(),'L LT').add('h', 2); 
                        var end_cur = moment($( "#endDate" ).val() + ' ' + $( "#endTime" ).val(),'L LT').add('h', 2);
                        var title = $( "#title" ).val();
                        var description = $( "#description" ).val();
                        var id = $( "#id" ).val();
                        var allDay = $( "#allDay" ).is( ":checked" );
                        var uid = $( "#user option:selected" ).val();
                        var visibility = $( "#visibility option:selected" ).val();
                        var category = $( "#category option:selected" ).val();
                        var prio = $( "input:radio:checked[name='prioRadio']" ).val();
                        var job  = $( "input:radio:checked[name='jobRadio']" ).val();
                        var color = $( "#color" ).val();
                        var done = $( "#done" ).is( ":checked" );
                        var location = $( "#location" ).val();
                        if ( location == '' ) {
                            var cust_vend_pers = '';
                        } else {
                            var cust_vend_pers = $( "#cust_vend_pers" ).val();
                        };
                        var cust_vend_pers_old = $( "#cust_vend_pers_old" ).val();
                        var repeat = $( "#repeat" ).val();
                        var repeat_factor = $( "#repeat_factor" ).val();
                        var repeat_quantity = $( "#repeat_quantity" ).val();
                        var repeat_end =  moment($( "#repeat_end" ).val() + ' 23:59:59' ,'L LT');
                        if ( title ) {
                            event = { //wird benötigt???
                                title: title,
                                description: description,
                                start: start_cur,
                                end: end_cur,
                                id : id,
                                allDay: allDay,
                                uid : uid,
                                visibility : visibility,
                                category : category,
                                prio: prio,
                                job:    job,
                                color: color,
                                done:  done,
                                location:location,
                                cust_vend_pers:cust_vend_pers,
                                cust_vend_pers_old:cust_vend_pers_old,
                                repeat:repeat,
                                repeat_factor:repeat_factor,
                                repeat_quantity:repeat_quantity,
                            } //end event
                            start = moment(start).format( "YYYY-MM-DD HH:mm:ss");
                            end = moment(end).format( "YYYY-MM-DD HH:mm:ss");
                            repeat_end = moment(repeat_end).format( "YYYY-MM-DD HH:mm:ss");
                            $.ajax({
                                url: 'jqhelp/calendar.php',
                                data: {
                                    task:  $("#id").val() ? 'updateEvent' : 'newEvent', 
                                    title: $("#title").val(),
                                    description: $("#description").val(),
                                    id:   $("#id").val(),
                                    allDay: $( "#allDay" ).is( ":checked" ),
                                    uid : $("#user option:selected").val(),
                                    visibility : visibility,
                                    category : $( "#category option:selected" ).val(),  
                                    start: start,
                                    end: end, 
                                    prio: prio,
                                    job : job,
                                    color: color,
                                    done: done,
                                    location: location,
                                    cust_vend_pers: cust_vend_pers,
                                    cust_vend_pers_old: cust_vend_pers_old,
                                    repeat:repeat,
                                    repeat_factor:repeat_factor,
                                    repeat_quantity:repeat_quantity,
                                    repeat_end:repeat_end,
                                },
                                type: "POST",
                                error: function () {
                                    alert('Ajax Error');
                                },
                                success: function (rc) {
                                    console.log('Gesichert');
                                    NewEvent = true;
                                }
                            }) //end ajax
                            //Aktiven Tab suchen und Calendar aktualisieren
                            var activeTab = $("#tabs .ui-tabs-panel:visible").attr("id");
                            //console.log('AktivTab' + activeTab )
                            $( "#tabs-1 div:first-child" ).fullCalendar( 'refetchEvents' ); 
                            if ( $( "#category option:selected" ).val() > 0 ) {
                                $( "#calendargetCategory"+$( "#category option:selected" ).val() ).fullCalendar( 'refetchEvents' ); 
                            }
                            //console.log('User' + $( "#user option:selected" ).val() );
                            if ( $( "#user option:selected" ).val() > 0 ) {
                                $( "#calendargetUsers"+$( "#user option:selected" ).val() ).fullCalendar( 'refetchEvents' ); 
                            }
                            //Tabs vom User und der Category aktualisieren wenn diese sich ändern
                            //Machen wir erst beim Aktivieren
                            //if( uid != $( "#tmp" ).data( "uid" ) ) $( "#calendargetUsers" + uid ).fullCalendar( 'refetchEvents' );
                            //if( category != $( "#tmp" ).data( "category" ) ) $( "#calendargetCategory" + category ).fullCalendar( 'refetchEvents' );
                        } //end if title
                        else alert('Title is empty'); //ToDo                 
                        $( this ).dialog( "close" );
                    }, //end save
                    Delete: function() { 
                        var id = $( "#id" ).val(); 
                        var activeTab = $("#tabs .ui-tabs-panel:visible").attr("id");
                        if( id ) $( "#" + activeTab + " div:first-child" ).fullCalendar( 'removeEvents', id );                
                        $.ajax({
                            url: 'jqhelp/calendar.php',
                            data: {
                                task:  'deleteEvent',
                                id: $("#id").val() 
                            },
                            type: "POST",
                            success: function() {
                                //alert( "Event gelöscht"  );
                            },
                            error: function () {
                                alert('Ajax Error');
                            }
                        }) 
             
                        $( this ).dialog( "close" );
                    },
                    Cancel: function() {                         
                        $( this ).dialog( "close" );
                    }
                },
                close: function() {                       
                    $( this ).dialog( "close" );
                }
            });//end dialog
            var calculate_end = function(){ 
                $( "#repeat_end" ).val( moment( $( "#endDate" ).val(), "L" ).add( $( "#repeat" ).val(), $( "#repeat_factor" ).val() * $( "#repeat_quantity" ).val() ).format( "L" ) ); 
            };
            var calculate_repeat_quantity = function() {
                var a = moment( $( "#endDate" ).val(), 'L' );
                var b = moment( $( "#repeat_end" ).val(), 'L' );
                var erg = Math.floor( ( b.diff( a, $( "#repeat" ).val() ) ) / $( "#repeat_factor" ).val() );
                $( "#repeat_quantity" ).val( erg < 0 ? 0 : erg );                   
            };
         
            /*** SelectBox User, Kategorie **********************************************************************************************/
            $("#user, #category").each(function(){
                var ajaxTask = this.id == 'user' ? 'getUsers': 'getCategory'; 
                $(this).selectBoxIt({
                    theme:      "jqueryui",
                    autoWidth:  true,
                    height:     "12",
                    populate: function() {
                        var deferred = $.Deferred()
                        $.ajax({
                            url: 'jqhelp/calendar.php',
                            data: { task: ajaxTask }
                        }).done(function(json) {
                            var obj = $.parseJSON( json.trim() ) ; 
                            var objCalendar = $.parseJSON( json.trim() ) ;
                            if( ajaxTask == 'getCategory' ){
                                objCalendar.unshift( {value: 0, text: "ALLE"} );
                                obj.unshift( {value: 0, text: ""} );
                            }
                            $.each( objCalendar, function( i, val ){
                                //Neuen Tab erzeugen
                                if( val.value != 0 ){
                                    $("div#tabs ul").append("<li id='"+ajaxTask + val.value+"'><a href='#tab" + ajaxTask+ val.value + "'>" + val.text + "</a></li>"); //Ok
                                    if ( ajaxTask == 'getUsers' && val.value != loginCRM) {
                                        if ( !$.cookie('getUsers') ) 
                                        $("#"+ajaxTask + val.value).hide();
                                        UGs.push(ajaxTask + val.value);
                                    }
                                    if ( ajaxTask == 'getCategory' ) {
                                        Cat.push(ajaxTask + val.value);
                                        if ( !$.cookie('getCategory') ) 
                                        $("#"+ajaxTask + val.value).hide();
                                    }
                                    $("div#tabs").append("<div id='tab" + ajaxTask + val.value + "'><div id='calendar" + ajaxTask + val.value + "'></div></div>");
                                }
                                $( "#tabs" ).tabs({active:$.cookie('activetab')});
                                //Calendar für Tabs erzeugen   
                                /*** Begin Calendar *********************************************************************************************************************/ 
                                $('#calendar' + ajaxTask + val.value  ).fullCalendar({
                                    lang: language,
                                    theme: true,
                                    header: {
                                        left: 'prev,next today',
                                        center: 'title',
                                        right: 'month, agendaWeek, basic2Weeks, agendaDay'
                                    },
                                    views: {
                                        agenda2Weeks: {
                                           type: 'agenda',
                                           duration: { days: 14 },
                                           buttonText: '2 Wochen'
                                        },
                                        basic2Weeks: {
                                           type: 'basic',
                                           duration: { days: 14 },
                                           buttonText: '2 Wochen'
                                        }
                                    },
                                    minTime: termbegin,
                                    maxTime: termend,
                                    slotDuration: '00:'+termseq+':00',
                                    weekNumbers: true,
                                    weekMode: 'liquid',
                                    editable: true,
                                    defaultView: defaultcal,
                                    dragble: true,
                                    selectable: true, 
                                    selectHelper: true,
                                    events: {
                                        url: 'jqhelp/calendar.php',
                                        data: { myuid: loginCRM, where: val.value == 0 ? '' : (ajaxTask == "getUsers" ? "uid = " + val.value + " AND" : "category = " + val.value + " AND") }
                                    },//end events
                                    /*** New Event ************************************************************************************/
                                    select: function( start, end ){
                                        $( "#title" ).val('');
                                        $( "#description" ).val('');
                                        $( "#id" ).val('');
                                        $( "#allDay ").prop( 'checked', false );//ToDo abfragen ob es allDay ist
                                        $( "#startDate" ).val( moment( start ).format( "L") );
                                        $( "#startTime" ).val( moment( start ).format( "LT") );
                                        $( "#endDate" ).val( moment( end ).format( "L") );
                                        $( "#endTime" ).val( moment( end ).format( "LT") );
                                        $( "#user" ).data("selectBox-selectBoxIt").selectOption( ajaxTask == 'getUsers' && $( "#tabs" ).tabs( "option", "active" ) != 0 ? val.value.toString() : loginCRM);
                                        $( "#category" ).data("selectBox-selectBoxIt").selectOption( ajaxTask == 'getCategory' && $( "#tabs" ).tabs( "option", "active" ) != 0 ? val.value.toString() : '0' );
                                        $( "#visibility" ).data( "selectBox-selectBoxIt" ).selectOption( '-1' );
                                        $( "#repeat" ).data( "selectBox-selectBoxIt" ).selectOption( 'day' );
                                        $( "#prio_1,#job_false" ).prop( 'checked', true );            
                                        $( "div#jobRadio,div#prioRadio" ).buttonset( "refresh" );
                                        $( "#color, #repeat_quantity" ).val( "" );
                                        $( "#repeat_factor,#repeat_quantity" ).val( '0' );
                                        $( "#colorPick" ).hide();
                                        $( "#done" ).prop( 'checked', false );
                                        $( "#location,#repeat_end" ).val('');
                                        $( "#tmp" ).data( "srcId", '' );
                                        $( "#cust_vend_pers" ).val( false ); 
                                        $( "#cust_vend_pers_old" ).val( false ); 
                                        $( "#repeat,#repeat_factor,#repeat_quantity" ).change( calculate_end );
                                        $( "#repeat_end" ).change( calculate_repeat_quantity );
                                        $( ":input[type!='button'][id!='done']" ).attr( "disabled", false ).css( "background","#FFF" );
                                        $( "div#jobRadio,div#prioRadio" ).buttonset("refresh");
                                        $( "#dialog" ).dialog( "open" );
                                    },//end select
                                    /*** Edit Event *************************************************************************************/
                                    eventClick: function( event ){       
                                        $( "#title" ).val( event.title );
                                        $( "#description" ).val( event.description ); 
                                        $( "#id" ).val( event.id );
                                        $( "#allDay" ).prop( 'checked', event.allDay );
                                        /*$("#allDay").button({ text: false}).click(function(e) {
                                            $(this).button("option", {
                                                icons: { primary: $(this)[0].checked ? "ui-icon-check" : "" }
                                            })
                                        })*/
                                        $( "#startDate" ).val( moment( event.start ).format( "L") );
                                        $( "#startTime" ).val( moment( event.start ).format( "LT") );
                                        $( "#endDate" ).val( moment( event.end ? event.end : event.start ).format( "L") );
                                        $( "#endTime" ).val( moment( event.end ? event.end : event.start ).format( "LT") );
                                        $( "#user" ).data( "selectBox-selectBoxIt" ).selectOption( String( event.uid ) );
                                        $( "#category" ).data("selectBox-selectBoxIt").selectOption( String( event.category ) );
                                        $( "#visibility" ).data("selectBox-selectBoxIt").selectOption( String( event.visibility ) );
                                        $( "#prio_" + event.prio ).prop( 'checked', true );
                                        if ( event.job == 't' || event.job == true ) { 
                                            $( "#job_true" ).prop( 'checked', true ); 
                                        } else {
                                            $( "#job_false" ).prop( 'checked', true ); 
                                        };
                                        $( "div#jobRadio,div#prioRadio" ).buttonset("refresh");
                                        $( "#colorPick" ).hide();
                                        $( "#color" ).val( event.color );
                                        $( "#cust_vend_pers" ).val( event.cust_vend_pers ); 
                                        $( "#cust_vend_pers_old" ).val( event.cust_vend_pers ); 
                                        $( "#tmp" ).data( "uid", event.uid ); 
                                        $( "#tmp" ).data( "category", event.category );
                                        $( "#location" ).val( event.location );
                                        $( "#done" ).prop( 'checked', event.done );
                                        $( "#repeat" ).data("selectBox-selectBoxIt").selectOption( event.repeat.trim() );
                                        $( "#repeat,#repeat_factor,#repeat_quantity" ).change( calculate_end );
                                        $( "#repeat_end").change( calculate_repeat_quantity );
                                        $( "#repeat_factor" ).val( event.repeat_factor );
                                        $( "#repeat_quantity" ).val( event.repeat_quantity );
                                        $( "#repeat_end" ).val( moment( event.repeat_end ).format( "L") == 'Invalid date' ? '' : moment( event.repeat_end ).format( "L")  );
                                        $( "#chkboxDone" )[event.job ? 'show' : 'hide']();
                                        $( ":input[type!='button'][id!='done']" ).attr( "disabled", event.done ).css( "background", event.done ? "#F8F8F3" : "#FFF" );
                                        $(".ui-button").attr("disabled", false);
                                        $( "div#jobRadio,div#prioRadio" ).buttonset("refresh");
                                        $( "#dialog" ).dialog( "open" );
                                    }, //end eventClick
                                    /*** Move Event *************************************************************************************/
                                    eventDrop: function(event) {
                                        var start = moment(event.start).format( "YYYY-MM-DD HH:mm:ss");
                                        var end  = event.end ? moment(event.end).format( "YYYY-MM-DD HH:mm:ss") : moment(event.start).add('h', 1).format( "YYYY-MM-DD HH:mm:ss"); //Warum eine Stunde addieren??
                                        $.ajax({
                                            url: 'jqhelp/calendar.php',
                                            data: {
                                                task:  'updateTimestamp', 
                                                start:  start,
                                                end:    end,
                                                id:     event.id ? event.id : $( "#id" ).val(),
                                                allDay: event.allDay
                                            },
                                            type: "POST",
                                            //success: function(json) {
                                            //alert('Event verschoben');
                                            //},
                                            error: function () {
                                                alert('Ajax Error');
                                            }
                                        });
                                    }, //end eventDrop
                                    /*** Rezize Time ********************************************************************************************/
                                    eventResize: function(event) {
                                        var start = moment(event.start).format( "YYYY-MM-DD HH:mm:ss");
                                        var end   = moment(event.end).format( "YYYY-MM-DD HH:mm:ss");
                                        $.ajax({
                                            url: 'jqhelp/calendar.php',
                                            data: {
                                                task:  'updateTimestamp', 
                                                start:  start,
                                                end:    end,
                                                id:     event.id,
                                                allDay: event.allDay
                                            },
                                            type: "POST",
                                            //success: function(json) {
                                                //alert('Zeit geändert');
                                            //},
                                            error: function () {
                                                alert('Ajax Error');
                                            }
                                        });
                                    },//end eventResize
                                }); //end Calendar
                                /*** End Calendar *****************************************************************************************************/
                            });//end $.each()
                            var T = ajaxTask.substr(3,1);
                            $("div#tabs ul").append("<li id='"+ajaxTask+"' style='padding-bottom:0' ><a href='#tab-"+ajaxTask+"' data-lang='Open' class='lang'><img src='image/"+ajaxTask+".png' height='12px' style='padding:0;' border='0'></a></li>"); 
                            //$("div#tabs ul").append("<li id='"+ajaxTask+"' style='padding-bottom:0' ><a href='#tab-"+ajaxTask+"' data-lang='Open' class='lang'>"+T+"+</a></li>"); 
                            $( "div#tabs" ).tabs( "refresh" );
                            deferred.resolve( obj );
                        }); 
                        return deferred;
                    } //end $.each populate
                }) //end selectBoxIt
            }) //end $.each "#user, #category"
            $("div#tabs ul").append("<li id='tabressource' style='padding-bottom:0' ><a href='ressourcen.phtml' data-lang='Open' class='lang'>Ressourcen</a></li>"); 
            $("#ressource").hide();
            var tabs = $( "#tabs" ).tabs({
                 autoAnchor: true,
                 active   : $.cookie('activetab'),
                 activate: function( event, ui ){
                    $.cookie( 'activetab', ui.newTab.index(),{ expires : 1  });
                    if ( ui.newPanel["selector"] == '#tab-getUsers') {
                        $( this ).removeClass("active");
                        if ( UserGrp ) {
                            for ( var i=0; i<UGs.length; i++) $( '#'+UGs[i] ).hide();
                        } else {
                            for ( var i=0; i<UGs.length; i++) $( '#'+UGs[i] ).show();
                        };
                        UserGrp = !UserGrp;
                        $.cookie( 'getUsers', UserGrp,{ expires : 1  });
                        $( "#tabs" ).tabs({active:0});
                    } else if ( ui.newPanel["selector"] == '#tab-getCategory') {
                        $(this).removeClass("active");
                        if ( Category ) {
                            for ( var i=0; i<Cat.length; i++) $( '#'+Cat[i] ).hide();
                        } else {
                            for ( var i=0; i<Cat.length; i++) $( '#'+Cat[i] ).show();
                        };
                        Category = !Category;
                        $.cookie( 'getCategory', Category,{ expires : 1  });
                        $( "#tabs" ).tabs({active:0});
                    } else if ( ui.newPanel["selector"] == '#tab-ressourcen') {
                        $("#ressource").show();
                    } else {
                        if ( $("#ressource").is(":visible") ) $("#ressource").hide();
                        //den angeklickten Calendar rendern
                        $( "#" + ui.newPanel.attr( 'id' ) + " div:first-child" ).fullCalendar( 'refetchEvents' ); 

                    }
                 }
            }); //end tabs
            $( "#visibility" ).selectBoxIt({
                theme:      "jqueryui",
                autoWidth:  true,
                height: "12",
                populate: grps 
            }); //end visibility
            $( "#repeat" ).selectBoxIt({
                theme:      "jqueryui",
                autoWidth:  true,
                height: "12",
                populate: [
                    { value: "day",  text: langData[language]['DAY'] },
                    { value: "week", text: langData[language]['WEEK'] },
                    { value: "month",text: langData[language]['MONTH'] },
                    { value: "year", text: langData[language]['YEAR'] }
                ]   
            }); //end repeat
            $( "#jobRadio,#prioRadio" ).buttonset();//.find('label').height(28);;
            $( "#job_true" ).click( function() {
                $( "#endDate" ).val( moment( $( "#startDate" ).val(), 'DD.MM.YYYY' ).add( 'years', 1 ).format( "L") );
                $( "#allDay" ).prop( 'checked', true );
                $( "#chkboxDone" ).show( "fast" );
            });
            $( "#job_false" ).click( function() {
                $( "#endDate" ).val( $( "#startDate" ).val()); // moment().format( "L" ) );
                if ( $( "#startTime" ).val() == '' || $( "#startTime" ).val() == '00:00 Uhr' ) {
                    $( "#startTime" ).val( moment().format( "LT") );
                    $( "#endTime" ).val( moment().add( "minutes", termseq ).format( "LT") ) ;
                };
                $( "#allDay" ).prop( 'checked', false ).change();
                $( "#chkboxDone" ).hide( "fast" );
            });
            $( "#prio_0" ).click( function(){           
                $( "#color" ).val( colors[3] );
            });
            $( "#prio_1" ).click( function(){           
                $( "#color" ).val( '' );
            });   
            $( "#prio_2" ).click( function(){           
                $( "#color" ).val( colors[10] );
            });

            $( "#done" ).click( function(){//
                var color = $( "#color" ).val();
                if ($( "#prio_0" ).is( ':checked' )) { 
                    color = colors[3];
                } else if ($( "#prio_2" ).is( ':checked' )) {
                    color = colors[10];
                };
                var pri0 = $( "#prio_0" ).is( ':checked' ) ? '0':'_';
                var pri1 = $( "#prio_1" ).is( ':checked' ) ? '1':'_';
                var pri2 = $( "#prio_2" ).is( ':checked' ) ? '2':'_';
                if( $( "#done" ).is( ':checked' ) ) {
                    $( "#tmp" ).data( "endDate", $( "#endDate" ).val() );   
                    $( "#tmp" ).data( "color", $( "#color" ).val() )
                    //color = $( "#color" ).val();
                    $( "#endDate" ).val( moment().format( "L") ); // Soll das wirklich so sein? Vor allem, wenn das Startdatum dahinter liegt! Besser endDate == planedEndDate + endDate == realEndDate
                    $( "#color" ).val( 'green' );
                    $(":input[type!='button'][id!='done']").attr("disabled", true).css("background","#F8F8F3");
                    $(".ui-button").attr("disabled", false);
                    $( "div#jobRadio,div#prioRadio" ).buttonset("refresh");
                } else {
                    //$( "#endDate" ).val( $( "#tmp" ).data( "endDate" ) ? $( "#tmp" ).data( "endDate" ) : moment().format("L"));//moment( $( "#endDate" ) ).add( 'years', 1 ).format( "L") );
                    $( "#tmp" ).data( "endDate", $( "#endDate" ).val() );   
                    $( "#color" ).val( $( "#tmp" ).data( "color" ) ? $( "#tmp" ).data( "color" ) : color );
                    $( ":input[type!='button'][id!='done']" ).attr( "disabled", false ).css( "background","#FFF" );
                    $( "div#jobRadio,div#prioRadio" ).buttonset("refresh");
                }
                    
            }); //end done
            $( "#color" ).click( function(){
                $( "#colorPick" ).toggle();
                var tmp = $.inArray($( '#color' ).val(),colors);
                if ( tmp > -1  ) {
                    $( 'div[style*="background-color:'+colors[tmp]+'"]' ).click()
                }
            });
            $('#colorPick').colorPicker({			
                //defaultColor: 1, 
                columns: 13,     // number of columns (optional)  
                color: colors,
                click: function(color){
                    $('#color').val(color);
                    $( "#colorPick" ).toggle();
                }, 
            }); //end colorPicker
            $.widget("custom.catcomplete", $.ui.autocomplete, {
                _renderMenu: function(ul,items) {
                    var that = this,
                    currentCategory = "";
                    $.each( items, function( index, item ) {
                        if ( item.category != currentCategory ) {
                            ul.append( "<li class=\'ui-autocomplete-category\'>" + item.category + "</li>" );
                            currentCategory = item.category;
                        }
                        that._renderItemData(ul,item);
                    });
                }
            }); //end widget
            $( "#location" ).change(function(){
                    //$( "#cust_vend_pers" ).val( false );
                    console.log("change");
                }).catcomplete({ 
                    source: "jqhelp/autocompletion.php?case=name",  
                    minLength: feature_ac_minlength,                       
                    delay: feature_ac_delay,
                    disabled: false,
                    select: function( e, ui ) {
                        var tmp = $( "#cust_vend_pers" ).val();
                        $( "#cust_vend_pers_old" ).val( tmp );
                        $( "#cust_vend_pers" ).val( ui.item.src+ui.item.id );
                    }
                }).dblclick(function() {
                    console.log("dblclick");
                    var cust_vend_pers = $( "#cust_vend_pers" ).val();
                    if ( cust_vend_pers== 'undefined' ) return;
                    if( cust_vend_pers != 'false' ) {
                        var Q  = cust_vend_pers.charAt( 0 );
                        window.open( "firma" + (Q=='K' ? '2' : '1') + ".php?Q=" + Q + "&id=" + cust_vend_pers.slice(1) );
                    } else {
                        if ( $( "#location" ).val() != '' )
                            window.open( "http://maps.google.de/maps/place/" + $( "#location" ).val() );
                    }
                }).tooltip( { position: { my: "center bottom-10", at: "center top" } } ); //end location
            $( "#allDay" ).change( function(){
                if( $(this).is( ":checked" ) ){
                    $( "#startTime" ).val( moment( "00:00", "HH:mm" ).format( "LT") );
                    $( "#endTime" ).val( moment( "00:00", "HH:mm" ).format( "LT") );
                    $( "#endDate" ).val( moment( $( "#startDate" ).val(), "L" ).add( 'DAY', 1 ).format( "L") );
                }
                if( !$(this).is( ":checked" ) ){
                    if ( $( "#startTime" ).val() == '00:00 Uhr' ) {
                        $( "#startTime" ).val( moment( termbegin , "HH:mm" ).format( "LT") );
                        $( "#endTime" ).val( moment( termbegin , "HH:mm" ).add( "minutes", termseq ).format( "LT") );
                    }
                }
            }); //end allDay
        });      ;//end init.done
    });//end document.ready
</script>
<style>
    .kalender {
        margin: 0;
        padding: 0;
        font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
        font-size: 14px;
    }

    .ui-autocomplete-category {
        font-weight: bold;
        padding: .2em .4em;
        margin: .8em 0 .2em;
        line-height: 1.5;
    }
    .fc-sat { color:blue; background:#e5e5e5; }
    .fc-sun { color:red;  background:#e5e5e5; }
    #titleLabel         { position:absolute; top:20px; left:32px; }
    #titleInp           { position:absolute; top:20px; left:95px;}
    #jobRadio           { position:absolute; top:10px; left:465px;}
    #start              { position:absolute; top:50px; left:32px; }
    #startDateInp       { position:absolute; top:50px; left:95px;}
    #startTimeInp       { position:absolute; top:50px; left:195px; }
    #chkboxAllDay       { position:absolute; top:48px; left:295px; }
    #chkboxDone         { position:absolute; top:78px; left:295px; }
    #colorLabel         { position:absolute; top:50px; left:475px; }
    #colorInp           { position:absolute; top:50px; left:550px; }
    #colorPick          { position:absolute; top:70px; left:450px; z-index: 1; }
    #end                { position:absolute; top:80px; left:32px; }
    #endDateInp         { position:absolute; top:80px; left:95px; }
    #endTimeInp         { position:absolute; top:80px; left:195px;}
    #categoryLabel      { position:absolute; top:120px; left:34px; }
    #categoryDrop       { position:absolute; top:140px; left:32px;}
    #userLabel          { position:absolute; top:120px; left:220px; }
    #userDrop           { position:absolute; top:140px; left:218px;}
    #visibilityLabel    { position:absolute; top:120px; left:400px; }
    #visibilityDrop     { position:absolute; top:140px; left:400px;}
    #prioLabel          { position:absolute; top:100px; left:350px; }
    #prioRadio          { position:absolute; top:90px; left:412px;}
    #locationLabel      { position:absolute; top:173px; left:32px;}
    #locationInput      { position:absolute; top:190px; left:30px;}
    #locationInfo       { position:absolute; top:200px; left:500px;}
    #repeatLabel        { position:absolute; top:173px; left:220px;}
    #repeatFactorInput  { position:absolute; top:190px; left:220px;}
    #repeatSelect       { position:absolute; top:190px; left:270px;}
    #repeatQuantityInput{ position:absolute; top:190px; left:400px;}
    #repeatEndInput     { position:absolute; top:190px; left:500px;}
    #descTitle          { position:absolute; top:220px; left:30px;}
    #description        { position:absolute; top:220px; left:30px;}
    .title{
         width: 350px;
    }    
    .date{
         width: 90px;
    }
    .time{
         width: 80px;
    }
    .location{
         width: 155px;
    } 
    .repeatfactor{
         width: 30px;
         text-align: right;
    }
    .inp-checkbox+label {
        margin: .5em;
        width:16px; 
        height:16px; 
        vertical-align:middle;
    }
    .selectboxit-container .selectboxit-options {width: 125px;}      
    .selectboxit-container span, .selectboxit-container .selectboxit-options a {height: 25px; line-height: 25px;}
    #repeatSelectBoxItContainer.selectboxit-container .selectboxit-options {width: 70px;}
    /*.radio+label{ */ 
       /* height: 25px;/*ToDo Buttonhöhe verringern*/
    /*};//​ */
        
</style>


</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:722px; border:0px;">
<h1 class="toplist  ui-widget  ui-corner-all tools content1" onClick="help('Kalender');"><span class='lang' data-lang='CALENDARRESSOURCE' ></span></h1><br>

    <div class="ui-widget-content kalender" style='border:0px;'>
    <div id="dialog" class="event-dialog" title="Event">
        <div id="dialog-inner">
            <div id="titleLabel">
              <b data-lang='TITLE' class='lang'></b> 
            </div> 
            <div id="titleInp">
                <input type="text"  id="title" class=" ui-widget-content ui-corner-all title">
                <input type="text"  name="id" id="id"  style="visibility: hidden" class="ui-widget-content ui-corner-all">
                <input type="text"  name="cust_vend_pers" id="cust_vend_pers"  style="visibility: hidden" >
                <input type="text"  name="cust_vend_pers_old" id="cust_vend_pers_old"  style="visibility: hidden" >
            </div>
            <div id="jobRadio">
                <form>
                    <input type="radio" id="job_false" class="radio" name="jobRadio" value='0'><label for="job_false" data-lang='TERM' class='lang'></label>
                    <input type="radio" id="job_true" class="radio" name="jobRadio" value='1' ><label for="job_true" data-lang='JOB' class='lang'></label>
                </form>
            </div>            
            <div id="start">
              <b>Start: </b> 
            </div>    
            <div id="startDateInp">
                <input type="text"   id="startDate" class="text ui-widget-content ui-corner-all date">
            </div>
            <div id="chkboxAllDay"><input class="inp-checkbox" id="allDay"  type="checkbox"><label for="allDay" data-lang='ALLDAY' class='lang' ></label></div>
            <div id="chkboxDone" style="display: none"><input class="inp-checkbox" id="done"  type="checkbox"><label for="done" data-lang='DONE' class='lang'></label></div> 
                <div id="colorLabel" data-lang='COLOR' class='lang' ></div>  
            <div id="colorInp">
                <input type="text"  id="color" class="text ui-widget-content ui-corner-all date">
            </div>
            <div id="colorPick" style="display: none"></div>
            <div id="startTimeInp">
                <input type="text"   id="startTime" class="text ui-widget-content ui-corner-all time">
            </div>
            <div id="end">
              <b data-lang='END' class='lang'></b> 
            </div>    
            <div id="endDateInp">
                <input type="text"   id="endDate" class="text ui-widget-content ui-corner-all date">
            </div>
            <div id="endTimeInp">
                <input type="text"   id="endTime" class="text ui-widget-content ui-corner-all time">
            </div>
            <div id="categoryLabel" data-lang='CATEGORY' class='lang'>
            </div> 
            <div id="categoryDrop">
                <select  id="category">
                </select> 
            </div>
            <div id="userLabel" data-lang='USER' class='lang'>
            </div> 
            <div id="userDrop">
                <select id="user" >
                </select> 
            </div>
            <div id="visibilityLabel" data-lang='VISIBILITY' class='lang'>
            </div>
            <div id="visibilityDrop">
                <select id="visibility">
                </select> 
            </div>
            <div id="prioLabel" data-lang='PRIORITY' class='lang' >
            </div>
            <div id="prioRadio">
                <form>
                    <input type="radio" id="prio_0" name="prioRadio" value='0' ><label for="prio_0" data-lang='MINOR'  class='lang'></label>
                    <input type="radio" id="prio_1" name="prioRadio" value='1' ><label for="prio_1" data-lang='NORMAL' class='lang'></label>
                    <input type="radio" id="prio_2" name="prioRadio" value='2' ><label for="prio_2" data-lang='MAJOR'  class='lang'></label>
                </form>                
            </div> 
            <div id="locationLabel" data-lang='CUSTOMER_LOCATION' class='lang'></div>
            <div id="locationInput">
                <form>
                    <input type="text"  id="location" class="ui-widget-content ui-corner-all location lang" autocomplete="off" data-lang='DOUBLE_KLICK'>    
                </form>    
            </div>          
            <div id="repeatLabel" data-lang='REPS' class='lang'></div>          
            <div id="repeatFactorInput">
                <form>
                    <input type="text"  id="repeat_factor" class=" ui-widget-content ui-corner-all repeatfactor " > -     
                </form>
            </div> 
            <div id="repeatSelect">   
                <select id="repeat" ></select> 
            </div>  
            <div id="repeatQuantityInput">
                <form>
                    <input type="text"  id="repeat_quantity" class=" ui-widget-content ui-corner-all repeatfactor lang"><span data-lang="BY_UNTIL" class="lang"></span> 
                </form>
            </div> 
            <div id="repeatEndInput">
                <form>
                    <input type="text"  id="repeat_end" class=" ui-widget-content ui-corner-all date" >    
                </form>
            </div> 
            <textarea name="description" id="description" class="text ui-widget-content ui-corner-all" rows="10" cols="64"></textarea>
        </div><!-- End dialog-inner -->               
    </div><!-- End dialog -->
    <div id="tabs" style='border:0px;'>
        <ul>
            <li id='taball' ><a href="#tabs-1" data-lang='ALL'  class='lang'></a></li>
        </ul>
        <div id="tabs-1">
            <div id="calendargetCategory0"></div>    
        </div>
        <div id="ressource">
        </div>

    </div><!-- End tabs -->
    </div><!-- End class kalendar -->
    <div id="tmp"></div>
<?php 
 echo $menu['end_content'];
?>
</body>
</html>
