<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<?php
    require_once("inc/stdLib.php");
    $menu = $_SESSION['menu'];
    $head = mkHeader();
    echo $menu['stylesheets'];
    echo $menu['javascripts'];
    echo $head['CRMCSS'];
    echo $head['BOXCSS'];
    echo $head['THEME'];
    echo $head['JQTABLE'];
    echo $head['JQBOX'];
    echo $head['JQTIME'];

?>
<script language="javascript" type="text/javascript" src="translation/fahrtenbuch.lng"></script>
<script>
    var loginCRM    = 0;
    function getLast() {
        console.log('getLast');
        $.ajax({                        //"Session"-Vars holen
                url: 'jqhelp/fahrtenbuch.php',
                //dataType: 'json',
                type: "POST",
                data: { task:  'getLast', id: loginCRM }
        }).done(function(json) {
            console.log(json);
            $( '#datatable tbody' ).empty().append(json); //append(json);
            $( '#datatable').trigger('update');
        })

    }
    function getFahrer() {
        console.log('getFahrer');
        $.ajax({                        //"Session"-Vars holen
                url: 'jqhelp/fahrtenbuch.php',
                dataType: 'json',
                type: "POST",
                data: { task:  'getFahrer', id: loginCRM }
        }).done(function(json) {
            console.log(json);
            $( '#KmStart' ).val(json['stopkm']);
            $( '#Fahrzeug' ).val(json['fahrzeug']);
        })
    }
    $( document ).ready( function(){
        var language    = kivi.myconfig.countrycode;    
        var initOptions = { theme : 'blue' };
        var uid         = 0;

        $( '#datatable' ).tablesorter({widthFixed: false, widgets: ['zebra'], widgetOptions : { zebra : [ "even", "odd" ]},debug: true });

        $.ajax({                        //"Session"-Vars holen
                url: 'jqhelp/fahrtenbuch.php',
                dataType: 'json',
                type: "POST",
                data: { task:  'initUser', }
        }).done(function(json) {
            console.log(json);
            console.log(json['loginCRM']);
            loginCRM    = json['loginCRM'];
        }) 
         
        $.ajax({
            url: 'jqhelp/fahrtenbuch.php',
            type: "POST",
            data: { task: 'getUsers' },
        }).done(function(data) {
            console.log('getUser');
            $( '#Fahrer' ).selectBoxIt({
                populate: $.parseJSON( data.trim() )
            });
            //$( '#Fahrer' ).val( loginCRM );
            $( '#Fahrer' ).data("selectBox-selectBoxIt").selectOption(loginCRM);
            uid = loginCRM;
            console.log(uid);
            getFahrer();
            getLast();
        });
        $( '#Fahrer' ).on('change',function() {
            var id = this.value ;
            console.log(id);
            loginCRM = id;
        });
        $( ".lang" ).each( function(){
            var key = $( this ).attr( "data-lang" );
            $( this ).text( typeof( langData[language][key] ) != 'undefined' ? langData[language][key] : 'LNG ERR'  );
        });

        $( '#Fahrer' ).on('change',function() {
            uid  = $( '#Fahrer option:selected' ).val();
            getLast();
            getFahrer();
            console.log('User:'+uid);
        });
        $( "#Datum" ).datepicker($.datepicker.regional[ "de" ])
                     .datepicker("setDate",new Date())
                     .datepicker( "option", "dateFormat", 'dd.mm.yy' );
        $( "#StartTime" ).timepicker({showPeriodLabels: false,hourText:langData[language]['Hour']});
        $( "#StopTime" ).timepicker({showPeriodLabels: false,hourText:langData[language]['Hour']});
        
        $( '#sichern' ).button().click( function() {
            console.log('Sichern');
            var Datum_       = $( '#Datum' ).val();    
            var Fahrzeug_    = $( '#Fahrzeug' ).val();   
            if ( Fahrzeug_ == '' ) { alert('Kein Fahrzeug angegeben'); return; };
            var StartTime_   = $( '#StartTime' ).val(); 
            var StopTime_    = $( '#StopTime' ).val(); 
            var re           = /^([01]?\d|2[0-3]):([0-5]?\d)$/
            if ( !StartTime_.match(re) ) { alert('Fehlerhafte Zeitangabe (Start)'); return; };
            if ( !StopTime_.match(re) ) { alert('Fehlerhafte Zeitangabe (Stop)'); return; };
            if ( StartTime_ >= StopTime_ ) { console.log('zeit'); $( 'msg' ).val('Endezeit muß größer sein.'); return; };
            var KmStart_     = $( '#KmStart' ).val();   
            var KmStop_      = $( '#KmStop' ).val();    
            if ( KmStart_ >= KmStop_ ) { alert('Endkilometer muß größer sein.'); return; };
            var Grund_       = $( '#Grund' ).val();  
            console.log(Datum_);
            console.log(Fahrzeug_);
            $.ajax({
                    url: 'jqhelp/fahrtenbuch.php',
                    dataType: 'json',
                    type: 'POST',
                    data: { task:  'sichern', Datum: Datum_, Fahrzeug: Fahrzeug_, StartTime: StartTime_, StopTime: StopTime_,
                            KmStart: KmStart_, KmStop: KmStop_, Grund: Grund_, Fahrer: loginCRM },
                }).done(function(rc) {
                console.log(rc);
                      if ( rc ) {
                          $( '#StartTime' ).val(''); 
                          $( '#StopTime' ).val('');  
                          $( '#KmStart' ).val(KmStop_);   
                          $( '#KmStop' ).val('');    
                          $( '#Grund' ).val('');  
                          $( '#msg' ).empty().append('Daten gesichert');
                          getLast();
                      } else {
                          $( '#msg' ).empty().append('Daten nicht gesichert!');
                      }
                })
        });
    }); //end document ready

</script>
</head>
<body>
<?php 
    echo $menu['pre_content'];
    echo $menu['start_content'];
?>
<div class="ui-widget-content" style="height:722px; border:0px;">
<h1 class="toplist  ui-widget  ui-corner-all content1" onClick="help('Fahrtenbuch');"><span class='lang' data-lang='HEADLINE'></span></h1>
 [<a href='fbauswertung.phtml'>zur Auswertung</a>]<br><br>
    <span class='inline'>
        <span id="UserLabel" data-lang='USER' class='lang'></span> 
        <span id="UserDrop">
            <select id="Fahrer" >
            </select> 
        </span>
        <span id='msg' style='font-size:14px; font-weight: bold; color:red'>neue Eingabe</span>
        <br/>
        <span id='zusatz'></span>
        <span id="Dates">
             <table>
             <tr><td><span data-lang='DATE'    class='lang'></span></td>
                 <td><span data-lang='AUTO'    class='lang'></span></td>
                 <td><span data-lang='START'   class='lang'></span></td>
                 <td><span data-lang='STOP'    class='lang'></span></td>
                 <td><span data-lang='KMSTART' class='lang'></span></td>
                 <td><span data-lang='KMSTOP'  class='lang'></span></td>
                 <td><span data-lang='GRUND'   class='lang'></span></td>
                 <td></td></tr>
             <tr><td><input type="text"  id="Datum"      size='10'></td>
                 <td><input type="text"  id="Fahrzeug"   size='10'></td>
                 <td><input type="text"  id="StartTime"  size='6' class="time"></td>
                 <td><input type="text"  id="StopTime"   size='6' class="time"></td>
                 <td><input type="text"  id="KmStart"    size='6'></td>
                 <td><input type="text"  id="KmStop"     size='6'></td>
                 <td><input type="text"  id="Grund"      size='30'></td>
                 <td><button id="sichern"  class="lang buttons" data-lang="SAVE"></button></td></tr>
            </table> 
        </span>
    </span>
    <br>

    <table id='datatable' class='tablesorter' style='margin:0px; cursor:pointer; border:0px;'>
        <thead>
        <tr><th><span data-lang='DATE'    class='lang'></th><th><span data-lang='AUTO'    class='lang'></span></th>
            <th><span data-lang='START'   class='lang'></span></th><th><span data-lang='STOP'    class='lang'></span></th>
            <th><span data-lang='KMSTART' class='lang'></span></th><th><span data-lang='KMSTOP'  class='lang'></span></th>
            <th><span data-lang='GRUND'   class='lang'></span></th></tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<?php echo $menu['end_content']; ?>
</body>
</html>
