-- @tag: Analysis
-- @description: Berichte über Umsätze

--Starttag
CREATE TABLE analysistyp(
    id      serial NOT NULL PRIMARY KEY,
    label   text,
    bericht text UNIQUE,
    sql     text,
    felder  text,
    orders  text,
    header  text,
    legend  text,
    xaxis   text,
    xlabel  text,
    note    text
);
INSERT INTO analysistyp (label,bericht,orders,header,legend,xaxis,xlabel,sql) VALUES ('Tagesumsätze','T1','monat','{"Betrag":"%0.2f","Verk\u00e4ufe":"%d","Datum":"date"}','{"Betrag":"betrag","Rechnungen":"cnt"}','monat','Monat','SELECT SUM(netamount) AS betrag,COUNT(*) AS cnt,to_char(transdate,''YYYYMM'') AS monat FROM ar WHERE ar.transdate >= ''#VONDATE#'' AND ar.transdate <= ''#BISDATE#'' GROUP BY monat ORDER BY');
INSERT INTO analysistyp (label,bericht,felder,orders,header,legend,xaxis,xlabel,sql,note) VALUES ('Monatsumsätze','M1','monat','Umsatz1:Hsum(netamount);Umsatz2:Hsum(netamount)','{"Betrag":"%0.2f","Anzahl":"%d","Monat/Jahr":"jamo"}','{"Betrag":"betrag","Anzahl":"cnt"}','monat','Monat','SELECT SUM(netamount) AS betrag,COUNT(*) AS cnt,to_char(transdate,''YYYYMM'') AS monat FROM ar to_char(transdate,''YYYY-MM'') >= ''#VONDATE#'' AND to_char(transdate,''YYYY-MM'') <= ''#BISDATE#'' #WHERE# GROUP BY monat #HAVING# ORDER BY','Anzahl Rechnungen und Umsatz je Monat');
INSERT INTO analysistyp (label,bericht,orders,header,legend,xaxis,xlabel,sql) VALUES ('Umsatz je Kunde','U1','customernumber','{"Umsatz":"%0.2f","Eink\u00e4ufe":"%d","Kd-ID":"%d","Kd-Nr":"%s","Name":"%s"}','{"Umsatz":"betrag","Eink\u00e4ufe":"cnt"}','customernumber','Kunde','SELECT SUM(netamount) AS betrag,COUNT(*) AS cnt,customer_id,customernumber,name||'' ''||zipcode||'' ''||city as nameort FROM ar LEFT JOIN customer ON customer_id=customer.id WHERE ar.transdate >= ''#VONDATE#'' AND ar.transdate <= ''#BISDATE#'' GROUP BY customer_id,customernumber,nameort ORDER BY');
INSERT INTO analysistyp (label,bericht,orders,header,legend,xaxis,xlabel,sql) VALUES ('Umsatz je Kunde / Monat','U2','customernumber,monat','{"Umsatz":"%0.2f","Eink\u00e4ufe":"%d","Kd-ID":"%d","Kd-Nr":"%s","Name":"%s","Monat":"%s"}','{"Umsatz":"betrag","Eink\u00e4ufe":"cnt"}','monat','Monat','SELECT SUM(netamount) AS betrag,COUNT(*) AS cnt,customer_id,customernumber,name||'' ''||zipcode||'' ''||city AS nameort,to_char(transdate,''YYYYMM'') AS monat FROM ar LEFT JOIN customer ON customer_id=customer.id WHERE ar.transdate >= ''#VONDATE#'' AND ar.transdate <= ''#BISDATE#'' #WHERE# GROUP BY customer_id,customernumber,nameort,monat ORDER BY');
INSERT INTO analysistyp (label,bericht,orders,header,legend,xaxis,xlabel,sql) VALUES ('Umsatz je Tag','U3','day','{"Umsatz":"%0.2f","Verk\u00e4ufe":"%d","Tag":"%s"}','{"Umsatz":"betrag","Verk\u00e4ufe":"cnt"}','day','Tag','SELECT SUM(netamount) AS betrag,COUNT(*) AS cnt,to_char(transdate,''DD'') AS day FROM ar WHERE to_char(transdate,''YYYY-MM'') = ''#VONYYYYMM#'' GROUP BY day ORDER BY ');
INSERT INTO analysistyp (label,bericht,orders,header,legend,xaxis,xlabel,sql) VALUES ('Verkaufte Artikel 1','U4','partnumber','{"Menge":"%0.2f","Umsatz":"%0.2f","Preis":"%0.2f","Artikelnummer":"%s","Bezeichnung":"%s"}','{"Menge":"cnt","Umsatz":"betrag"}','partnumber','Artikel','SELECT sum(qty) as cnt,a.sellprice*sum(qty) as betrag,a.sellprice,partnumber,a.description FROM ar LEFT JOIN invoice a ON ar.id=a.trans_id LEFT JOIN parts p ON p.id=a.parts_id LEFT JOIN partsgroup pn ON pn.id=p.partsgroup_id LEFT JOIN customer c ON c.id=ar.customer_id WHERE ar.transdate >= ''#VONDATE#'' AND ar.transdate <= ''#BISDATE#'' #WHERE# GROUP by partnumber,a.sellprice,a.description ORDER BY');
INSERT INTO analysistyp (label,bericht,orders,header,legend,xaxis,xlabel,sql) VALUES ('Verkaufte Artikel 2','U5','partnumber','{"Menge":"%0.2f","Artikelnummer":"%s","Umsatz":"%0.2f"}','{"Menge":"cnt","Umsatz":"betrag"}','partnumber','Artikel','SELECT sum(qty) as cnt,partnumber,sum(a.sellprice * qty) as betrag FROM ar LEFT JOIN invoice a ON ar.id=a.trans_id LEFT JOIN parts p ON p.id=a.parts_id LEFT JOIN partsgroup pn ON pn.id=p.partsgroup_id LEFT JOIN customer c ON c.id=ar.customer_id WHERE ar.transdate >= ''#VONDATE#'' AND ar.transdate <= ''#BISDATE#'' #WHERE# GROUP by partnumber ORDER BY');
INSERT INTO analysistyp (label,bericht,felder,orders,header,legend,xaxis,xlabel,sql) VALUES ('Umsatz nach Wochentag','U6','Artikelnummer:p.partnumber','wt','{"Umsatz":"%0.2f","Verk\u00e4ufe":"%d","Wt":"%s"}','{"Umsatz":"betrag","Verk\u00e4ufe":"cnt"}','wt','Umsatz nach Wochentag 1=So ','SELECT SUM(netamount) AS betrag,COUNT(*) AS cnt,to_char(ar.transdate,''D'') AS wt FROM ar LEFT JOIN invoice i ON i.trans_id=ar.id LEFT JOIN parts p ON p.id=parts_id WHERE ar.transdate >= ''#VONDATE#'' AND ar.transdate <= ''#BISDATE#'' #WHERE# GROUP BY wt ORDER BY ');
INSERT INTO analysistyp (label,bericht,felder,orders,header,legend,xaxis,xlabel,sql) VALUES ('Kasse: Umsatz je Tag','K1','Kasse:c.customernumber','std,kasse','{"Stunde":"%s","Umsatz":"%0.2f","Verk\u00e4ufe":"%d","Kasse":"%s"}','{"Umsatz":"betrag","Verk\u00e4ufe":"cnt"}','std','Stunde','SELECT substring(zeit from 1 for  2) as std,sum(summe) as betrag,count(b.*) as cnt,c.name as kasse FROM ekbon b LEFT JOIN customer c ON c.id=b.kasse WHERE (art = ''N'' OR art = ''S'') AND datum >= ''#VONDATE#'' AND datum <= ''#BISDATE#'' #WHERE# GROUP BY std,c.name ORDER BY');
INSERT INTO analysistyp (label,bericht,felder,orders,header,legend,xaxis,xlabel,sql) VALUES ('Kasse: Umsatz je Stunde','K2','Kasse:c.customernumber','std,kasse','{"Stunde":"%s","Umsatz":"%0.2f","Verk\u00e4ufe":"%d","Kasse":"%s"}','{"Umsatz":"betrag","Verk\u00e4ufe":"cnt"}','std','Stunde','SELECT substring(zeit from 1 for  2) as std,sum(summe) as betrag,count(b.*) as cnt,c.name as kasse FROM ekbon b LEFT JOIN customer c ON c.id=b.kasse WHERE (art = ''N'' OR art = ''S'') AND datum >= ''#VONDATE#'' AND datum <= ''#BISDATE#''  #WHERE# GROUP BY std,c.name ORDER BY');
INSERT INTO analysistyp (label,bericht,felder,orders,header,legend,xaxis,xlabel,sql) VALUES ('Kasse: Menge/Umsatz Artikel','K3','Kasse:c.customernumber','partnumber','{"Menge":"%0.2f","Umsatz":"%0.2f","Preis":"%0.2f","Artikelnummer":"%s","Bezeichnung":"%s"}','{"Menge":"cnt","Umsatz":"betrag"}','partnumber','Artikel','SELECT sum(menge) as cnt,preis*sum(menge) as betrag,preis,partnumber,description FROM ekartikel a LEFT JOIN parts p ON p.id=artikel LEFT JOIN ekbon b ON b.id=a.bon LEFT JOIN partsgroup pn ON pn.id=p.partsgroup_id LEFT JOIN customer c ON c.id=b.kasse WHERE datum >= ''#VONDATE#'' AND datum <= ''#BISDATE#'' #WHERE# GROUP by partnumber,preis,description ORDER BY');
INSERT INTO analysistyp (label,bericht,felder,orders,header,legend,xaxis,xlabel,sql) VALUES ('Kassenumsatz nach Wochentag','K4','Kasse:c.customernumber','wt,kasse','{"WT":"%s","Umsatz":"%0.2f","Verk\u00e4ufe":"%d","Kasse":"%s"}','{"Umsatz":"betrag","Verk\u00e4ufe":"cnt"}','wt','Wochentage 1=So 4=Mi 7=Sa','SELECT to_char(datum,''D'') AS wt,sum(summe) as betrag, count(b.*) AS cnt,c.name AS kasse  FROM ekbon b LEFT JOIN customer c ON c.id=b.kasse WHERE (art = ''N'' OR art = ''S'') AND datum >= ''#VONDATE'' AND datum <= ''#BISDATE#'' #WHERE# GROUP BY wt,c.name ORDER BY');
